/* Autogenerated by GitHub Action from schema file: ./v1/payments/schema.json. DO NOT MODIFY. */

export type Schema =
  | {
      $schema: string;
      payment_authorization: {
        quote_id: string;
        result: "success" | "failure";
        message?: string;
        timestamp: string;
        details: {
          network: "NEAR";
          token_type: "USDC";
          amount: number;
          account_id: string;
          transaction_id: string;
        }[];
        [k: string]: unknown;
      };
    }
  | {
      $schema: string;
      payment_result: {
        quote_id: string;
        result: "success" | "failure";
        timestamp: string;
        message?: string;
        details: {
          label: string;
          url?: string;
          value: string | number;
        }[];
        [k: string]: unknown;
      };
    }
  | {
      $schema: string;
      quote: {
        type: "Quote";
        quote_id: string;
        payee_id: string;
        payment_plans: {
          plan_id: string;
          plan_type: "one-time";
          amount: number;
          currency: "USD";
          [k: string]: unknown;
        }[];
        valid_until: string;
        [k: string]: unknown;
      };
    };
