# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: AITP
description: >- # this means to ignore newlines until "baseurl:"
  Agent Interaction & Transaction Protocol
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aitp.dev"
twitter_username: near_ai
github_username:  nearai
ga_tracking: G-SQ70S0ST9B
ga_tracking_anonymize-ip: true
aux_links:
  "Home":
    - "/"
  "GitHub":
    - "https://github.com/nearai/aitp"
aux_links_new_tab: false
nav_enabled: false # would need to set up ordering, hierarchy, etc.
callouts:
  note:
    title: Note
    color: blue

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/nearai/aitp"
gh_edit_branch: "main"
gh_edit_source: ""
gh_edit_view_mode: "tree"
mermaid:
  version: "11.4.1"

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme
