/* Autogenerated by GitHub Action from schema file: ./v1/data/schema.json. DO NOT MODIFY. */

export type Schema =
  | {
      $schema: string;
      data: {
        request_data_id?: string;
        /**
         * @minItems 1
         */
        fields: [
          {
            id: string;
            label?: string;
            value?: string;
            [k: string]: unknown;
          },
          ...{
            id: string;
            label?: string;
            value?: string;
            [k: string]: unknown;
          }[]
        ];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      $schema: string;
      request_data: {
        id: string;
        title?: string;
        description: string;
        fillButtonLabel?: string;
        form: {
          /**
           * @minItems 1
           */
          fields?: [
            {
              id: string;
              label?: string;
              description?: string;
              default_value?: string;
              type?: "text" | "number" | "email" | "textarea" | "select" | "combobox" | "tel";
              options?: string[];
              required?: boolean;
              autocomplete?: string;
              [k: string]: unknown;
            },
            ...{
              id: string;
              label?: string;
              description?: string;
              default_value?: string;
              type?: "text" | "number" | "email" | "textarea" | "select" | "combobox" | "tel";
              options?: string[];
              required?: boolean;
              autocomplete?: string;
              [k: string]: unknown;
            }[]
          ];
          json_url?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
