/* Autogenerated by GitHub Action from schema file: ./v1/decisions/schema.json. DO NOT MODIFY. */

export type Schema =
  | {
      $schema: string;
      decision: {
        request_decision_id?: string;
        /**
         * @minItems 1
         */
        options: [
          {
            id: string;
            name?: string;
            quantity?: number;
          },
          ...{
            id: string;
            name?: string;
            quantity?: number;
          }[]
        ];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      $schema: string;
      request_decision: {
        id: string;
        title?: string;
        description?: string;
        type?: "products" | "checkbox" | "radio" | "confirmation";
        /**
         * @minItems 1
         */
        options: [
          {
            id: string;
            name?: string;
            short_variant_name?: string;
            image_url?: string;
            description?: string;
            quote?: Quote;
            reviews_count?: number;
            five_star_rating?: number;
            url?: string;
            variants?: {
              id: string;
              name?: string;
              short_variant_name?: string;
              image_url?: string;
              description?: string;
              quote?: Quote;
              reviews_count?: number;
              five_star_rating?: number;
              url?: string;
              [k: string]: unknown;
            }[];
            [k: string]: unknown;
          },
          ...{
            id: string;
            name?: string;
            short_variant_name?: string;
            image_url?: string;
            description?: string;
            quote?: Quote;
            reviews_count?: number;
            five_star_rating?: number;
            url?: string;
            variants?: {
              id: string;
              name?: string;
              short_variant_name?: string;
              image_url?: string;
              description?: string;
              quote?: Quote;
              reviews_count?: number;
              five_star_rating?: number;
              url?: string;
              [k: string]: unknown;
            }[];
            [k: string]: unknown;
          }[]
        ];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };

export interface Quote {
  type: "Quote";
  quote_id: string;
  payee_id: string;
  payment_plans: {
    plan_id: string;
    plan_type: "one-time";
    amount: number;
    currency: "USD";
    [k: string]: unknown;
  }[];
  valid_until: string;
  [k: string]: unknown;
}
