# coding: utf-8

"""
    AITP Payments

    AITP Payments Specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr, validator

class PaymentPaymentPaymentMethod(BaseModel):
    """
    PaymentPaymentPaymentMethod
    """
    type: StrictStr = Field(default=..., description="Type of payment method used")
    token: StrictStr = Field(default=..., description="Token contract address")
    channel_id: StrictStr = Field(default=..., description="Identifier for the payment channel")
    amount: Optional[constr(strict=True)] = Field(default=None, description="Amount paid, as a string to prevent floating point imprecision")
    currency: StrictStr = Field(default=..., description="Currency code (e.g., 'USD')")
    __properties = ["type", "token", "channel_id", "amount", "currency"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('near_payment_channel',):
            raise ValueError("must be one of enum values ('near_payment_channel')")
        return value

    @validator('amount')
    def amount_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PaymentPaymentPaymentMethod:
        """Create an instance of PaymentPaymentPaymentMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PaymentPaymentPaymentMethod:
        """Create an instance of PaymentPaymentPaymentMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PaymentPaymentPaymentMethod.parse_obj(obj)

        _obj = PaymentPaymentPaymentMethod.parse_obj({
            "type": obj.get("type"),
            "token": obj.get("token"),
            "channel_id": obj.get("channel_id"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency")
        })
        return _obj


