# coding: utf-8

"""
    AITP Payments

    AITP Payments Specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, conlist
from aitp.stubs.models.affiliate import Affiliate

class RevenueShare(BaseModel):
    """
    Configuration for affiliate revenue sharing  # noqa: E501
    """
    affiliate_share_bps: StrictInt = Field(default=..., description="Percentage in basis points (1/100 of a percent) allocated to affiliates")
    affiliates: Optional[conlist(Affiliate)] = Field(default=None, description="List of affiliates that should receive a share")
    __properties = ["affiliate_share_bps", "affiliates"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RevenueShare:
        """Create an instance of RevenueShare from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in affiliates (list)
        _items = []
        if self.affiliates:
            for _item in self.affiliates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['affiliates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RevenueShare:
        """Create an instance of RevenueShare from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RevenueShare.parse_obj(obj)

        _obj = RevenueShare.parse_obj({
            "affiliate_share_bps": obj.get("affiliate_share_bps"),
            "affiliates": [Affiliate.from_dict(_item) for _item in obj.get("affiliates")] if obj.get("affiliates") is not None else None
        })
        return _obj


