# coding: utf-8

"""
    AITP Payments

    AITP Payments Specification

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr, validator

class TopUpResponseTopUpResponse(BaseModel):
    """
    TopUpResponseTopUpResponse
    """
    channel_id: StrictStr = Field(default=..., description="Identifier for the payment channel that was topped up")
    amount: constr(strict=True) = Field(default=..., description="Amount added to the channel, as a string to prevent floating point imprecision")
    currency: StrictStr = Field(default=..., description="Currency code (e.g., 'USD')")
    new_balance: Optional[constr(strict=True)] = Field(default=None, description="New balance in the channel, as a string to prevent floating point imprecision")
    payer_id: StrictStr = Field(default=..., description="Identifier for the payer")
    timestamp: datetime = Field(default=..., description="When the top-up was processed")
    payer_signature: StrictStr = Field(default=..., description="Cryptographic signature by the payer")
    __properties = ["channel_id", "amount", "currency", "new_balance", "payer_id", "timestamp", "payer_signature"]

    @validator('amount')
    def amount_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    @validator('new_balance')
    def new_balance_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TopUpResponseTopUpResponse:
        """Create an instance of TopUpResponseTopUpResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TopUpResponseTopUpResponse:
        """Create an instance of TopUpResponseTopUpResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TopUpResponseTopUpResponse.parse_obj(obj)

        _obj = TopUpResponseTopUpResponse.parse_obj({
            "channel_id": obj.get("channel_id"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "new_balance": obj.get("new_balance"),
            "payer_id": obj.get("payer_id"),
            "timestamp": obj.get("timestamp"),
            "payer_signature": obj.get("payer_signature")
        })
        return _obj


