ARG UBUNTU_VERSION=22.04
ARG PLATFORM=amd64
FROM --platform=${PLATFORM} ubuntu:${UBUNTU_VERSION} as base

ARG USER=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_VERSION=21.x

## Create unpriv user
RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -m $USER \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER

# Install dependencies
RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    git curl wget jq \
    build-essential ca-certificates default-jre \
    libudev-dev pkg-config libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install python & python deps
RUN apt-get update && \
    apt-get -y install --no-install-recommends python3 python3-dev python3-pip python3-setuptools python3-wheel && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install uv

# Install node
RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - && \
    apt-get install -y nodejs --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install node global deps
ARG OPENAPI_GENERATOR_VERSION=2.15.3
RUN npm install -g \
    @openapitools/openapi-generator-cli@${OPENAPI_GENERATOR_VERSION} \
    typescript \
    pnpm@latest-10
# Give user access to glob node_modules
RUN chown -R $USER: /usr/lib/node_modules

# Change to non-privileged user
USER $USER

## Install oh my zsh
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions
ENV PATH="/home/$USER/.oh-my-zsh/bin:/home/$USER/.local/bin:$PATH"
